#%RAML 0.8
title: Friends API
baseUri: http://localhost:3000/
protocols: [HTTP]
version: v1
schemas:
 - user: !include schemas/user.json
 - users: !include schemas/users.json
mediaType: application/json
/users:
  get:
    description: Get users list.
    responses:
      200:
        description: Users collection.
        body:
          application/json:
            schema: users
  /{userId}:
    uriParameters:
      userId:
        type: string
        description: The user uuid.
    get:
      description: User info
      responses:
        200:
          description: User info.
          body:
            application/json:
              schema: user
        404:
          description: User not found.
          body:
            application/json:
